# Generated by Django 3.0.8 on 2020-07-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('top', models.BooleanField(default=True)),
                ('bottom', models.BooleanField(default=True)),
                ('footgear', models.BooleanField(default=True)),
                ('headgear', models.BooleanField(default=True)),
                ('accessories', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
