# Generated by Django 3.0.8 on 2020-07-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_auto_20200722_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='category',
            field=models.CharField(choices=[('TOPS', 'Tops (shirts, sweaters, jackets,...)'), ('BTTM', 'Bottoms (shorts, pants, skirts,...)'), ('FTGR', 'Footgear (shoes, boots, sandals,...)'), ('HDGR', 'Headgear (glasses, hats, facial piercings,...)'), ('ACCS', 'Accessories (jewelry, belts, watches,...)')], default='TOPS', max_length=4),
        ),
    ]
